// JP-CES v0.1 editable backend data.
// IMPORTANT: These are DEMO values for testing the engine. Replace with approved, dated local rates.

const JP_DATA = {
  currency: "NPR",
  version: "0.1",
  demoRateProfile: {
    PRELIM_LS: {label:"Preliminaries", unit:"LS", rate:120000},
    EXCAVATION_M3: {label:"Excavation", unit:"m³", rate:800},
    BACKFILL_M3: {label:"Backfill & compaction", unit:"m³", rate:650},
    PCC_M3: {label:"PCC", unit:"m³", rate:13000},
    RCC_M3: {label:"RCC concrete excluding steel/formwork", unit:"m³", rate:19000},
    REBAR_KG: {label:"Reinforcement steel", unit:"kg", rate:120},
    FORMWORK_M2: {label:"Formwork", unit:"m²", rate:950},
    MASONRY_M3: {label:"Brick/block masonry", unit:"m³", rate:14500},
    PLASTER_M2: {label:"Plaster", unit:"m²", rate:560},
    FLOOR_M2_ECON: {label:"Economy floor finish", unit:"m²", rate:1500},
    FLOOR_M2_STD: {label:"Standard floor finish", unit:"m²", rate:2300},
    FLOOR_M2_PREM: {label:"Premium floor finish", unit:"m²", rate:4200},
    PAINT_M2: {label:"Painting system", unit:"m²", rate:520},
    DOOR_EACH_BASIC: {label:"Basic door set", unit:"No.", rate:22000},
    DOOR_EACH_STD: {label:"Standard door set", unit:"No.", rate:34000},
    DOOR_EACH_PREM: {label:"Premium door set", unit:"No.", rate:65000},
    WINDOW_EACH_AL: {label:"Aluminium window allowance", unit:"No.", rate:24000},
    WINDOW_EACH_UPVC: {label:"uPVC window allowance", unit:"No.", rate:31000},
    WINDOW_EACH_TIMBER: {label:"Timber window allowance", unit:"No.", rate:42000},
    WATERPROOF_M2: {label:"Waterproofing", unit:"m²", rate:950},
    BATHROOM_EACH: {label:"Bathroom plumbing + fixtures package", unit:"No.", rate:85000},
    KITCHEN_BASIC: {label:"Basic kitchen package", unit:"No.", rate:140000},
    KITCHEN_STD: {label:"Standard kitchen package", unit:"No.", rate:280000},
    KITCHEN_PREM: {label:"Premium kitchen package", unit:"No.", rate:550000},
    ELECTRICAL_POINT: {label:"Electrical point allowance", unit:"Point", rate:2800},
    SEPTIC_LS: {label:"Septic tank + soak pit allowance", unit:"LS", rate:220000},
    UGT_LS: {label:"Underground water tank allowance", unit:"LS", rate:180000},
    OHT_LS: {label:"Overhead tank + basic connection", unit:"LS", rate:75000},
    SLOPED_ROOF_M2: {label:"Sloped roof covering + frame allowance", unit:"m²", rate:4800},
    FALSE_CEILING_M2: {label:"False ceiling", unit:"m²", rate:1800},
    COMPOUND_WALL_M: {label:"Boundary wall allowance", unit:"m", rate:9500},
    PAVING_M2: {label:"Driveway / paving", unit:"m²", rate:2200},
    LANDSCAPE_LS: {label:"Basic landscaping allowance", unit:"LS", rate:100000},
    SOLAR_LS: {label:"Solar provision allowance", unit:"LS", rate:160000},
    AC_POINT: {label:"AC provision", unit:"Point", rate:18000},
    CCTV_LS: {label:"CCTV provision", unit:"LS", rate:85000},
    RETAINING_M: {label:"Retaining wall planning allowance", unit:"m", rate:28000}
  },
  assumptions: {
    RCC_CONCRETE_M3_PER_M2: 0.27,
    RCC_REBAR_KG_PER_M2_1F: 34,
    RCC_REBAR_KG_PER_M2_2F: 39,
    RCC_REBAR_KG_PER_M2_3PLUS: 43,
    FORMWORK_M2_PER_M2: 2.25,
    PCC_M3_PER_M2: 0.035,
    EXCAVATION_M3_PER_M2: 0.22,
    BACKFILL_FACTOR: 0.55,
    MASONRY_M3_PER_M2: 0.18,
    PLASTER_M2_PER_M2: 3.15,
    PAINT_M2_PER_M2: 3.55,
    FLOOR_FINISH_FACTOR: 0.94,
    FLAT_ROOF_WATERPROOF_FACTOR: 0.48,
    BATH_WATERPROOF_M2_EACH: 18,
    DEFAULT_STOREY_HEIGHT_M: 3.0,
    OVERHEAD_PROFIT_PCT: 10,
    CONTINGENCY_PCT: 5
  },
  kumariPreset: {
    projectName:"Kumari Gurung Residence",
    location:"Pokhara Ward 14",
    floors:2,
    gfArea:744.14,
    upperArea:551.07,
    hasPlan:"yes",
    slope:"flat",
    access:"easy",
    retaining:"no",
    soil:"unknown",
    bedrooms:3,
    bathrooms:2,
    kitchens:1,
    livingRooms:1,
    balconies:1,
    balconyArea:80,
    structure:"rcc",
    wall:"brick",
    roof:"flat",
    roofWaterproof:"yes",
    finish:"standard",
    windowType:"aluminium",
    doorType:"standard",
    ceiling:"plaster",
    sewer:"septic",
    ugt:"no",
    oht:"yes",
    kitchenPackage:"standard",
    electrical:"standard",
    solar:"no",
    ac:"no",
    cctv:"no",
    compound:"no",
    compoundLength:0,
    pavingArea:0,
    landscaping:"no"
  }
};
